package truthunfold.Constant;

public class EmailTemplate {

	public static String recoveryTemplate = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
			+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
			+ "\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
			+ "    <meta name=\"x-apple-disable-message-reformatting\">\r\n"
			+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
			+ "    <meta content=\"telephone=no\" name=\"format-detection\">\r\n"
			+ "    <title></title>\r\n"
			+ "    <!--[if (mso 16)]>\r\n"
			+ "    <style type=\"text/css\">\r\n"
			+ "    a {text-decoration: none;}\r\n"
			+ "    </style>\r\n"
			+ "    <![endif]-->\r\n"
			+ "    <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]-->\r\n"
			+ "    <!--[if gte mso 9]>\r\n"
			+ "<xml>\r\n"
			+ "    <o:OfficeDocumentSettings>\r\n"
			+ "    <o:AllowPNG></o:AllowPNG>\r\n"
			+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
			+ "    </o:OfficeDocumentSettings>\r\n"
			+ "</xml>\r\n"
			+ "<![endif]-->\r\n"
			+ "</head>\r\n"
			+ "\r\n"
			+ "<body>\r\n"
			+ "    <div class=\"es-wrapper-color\">\r\n"
			+ "        <!--[if gte mso 9]>\r\n"
			+ "			<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
			+ "				<v:fill type=\"tile\" color=\"#fafafa\"></v:fill>\r\n"
			+ "			</v:background>\r\n"
			+ "		<![endif]-->\r\n"
			+ "        <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
			+ "            <tbody>\r\n"
			+ "                <tr>\r\n"
			+ "                    <td class=\"esd-email-paddings\" valign=\"top\">\r\n"
			+ "                        <table class=\"es-content esd-footer-popover\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n"
			+ "                            <tbody>\r\n"
			+ "                                <tr>\r\n"
			+ "                                    <td class=\"esd-stripe\" style=\"background-color: #fafafa;\" bgcolor=\"#fafafa\" align=\"center\">\r\n"
			+ "                                        <table class=\"es-content-body\" style=\"background-color: #ffffff;\" width=\"600\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
			+ "                                            <tbody>\r\n"
			+ "                                                <tr>\r\n"
			+ "                                                    <td class=\"esd-structure es-p40t es-p20r es-p20l\" style=\"background-color: transparent; background-position: left top;\" bgcolor=\"transparent\" align=\"left\">\r\n"
			+ "                                                        <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
			+ "                                                            <tbody>\r\n"
			+ "                                                                <tr>\r\n"
			+ "                                                                    <td class=\"esd-container-frame\" width=\"560\" valign=\"top\" align=\"center\">\r\n"
			+ "                                                                        <table style=\"background-position: left top;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n"
			+ "                                                                            <tbody>\r\n"
			+ "                                                                                <tr>\r\n"
			+ "                                                                                    <td class=\"esd-block-image es-p5t es-p5b\" align=\"center\" style=\"font-size:0\"><a target=\"_blank\"><img src=\"https://tlr.stripocdn.email/content/guids/CABINET_dd354a98a803b60e2f0411e893c82f56/images/23891556799905703.png\" alt style=\"display: block;\" width=\"175\"></a></td>\r\n"
			+ "                                                                                </tr>\r\n"
			+ "                                                                                <tr>\r\n"
			+ "                                                                                    <td class=\"esd-block-text es-p15t es-p15b\" align=\"center\">\r\n"
			+ "                                                                                        <h1 style=\"color: #333333; font-size: 20px;\"><strong>FORGOT YOUR </strong></h1>\r\n"
			+ "                                                                                        <h1 style=\"color: #333333; font-size: 20px;\"><strong>&nbsp;PASSWORD?</strong></h1>\r\n"
			+ "                                                                                    </td>\r\n"
			+ "                                                                                </tr>\r\n"
			+ "                                                                                <tr>\r\n"
			+ "                                                                                    <td class=\"esd-block-text es-p40r es-p40l\" align=\"left\">\r\n"
			+ "                                                                                        <p style=\"text-align: center;\">HEY,</p>\r\n"
			+ "                                                                                    </td>\r\n"
			+ "                                                                                </tr>\r\n"
			+ "                                                                                <tr>\r\n"
			+ "                                                                                    <td class=\"esd-block-text es-p35r es-p40l\" align=\"left\">\r\n"
			+ "                                                                                        <p style=\"text-align: center;\">There was a request to change your password!</p>\r\n"
			+ "                                                                                    </td>\r\n"
			+ "                                                                                </tr>\r\n"
			+ "                                                                                <tr>\r\n"
			+ "                                                                                    <td class=\"esd-block-text es-p25t es-p40r es-p40l\" align=\"center\">\r\n"
			+ "                                                                                        <p>If you did not make this request, just ignore this email. Otherwise, please click the button below to change your password:</p>\r\n"
			+ "                                                                                    </td>\r\n"
			+ "                                                                                </tr>\r\n"
			+ "                                                                                <tr>\r\n"
			+ "                                                                                    <td class=\"esd-block-button es-p40t es-p40b es-p10r es-p10l\" align=\"center\"><span class=\"es-button-border\"><a href=\"http://localhost:8080/finalProject/account-recovery.jsp\" class=\"es-button\" target=\"_blank\">RESET PASSWORD</a></span></td>\r\n"
			+ "                                                                                </tr>\r\n"
			+ "                                                                            </tbody>\r\n"
			+ "                                                                        </table>\r\n"
			+ "                                                                    </td>\r\n"
			+ "                                                                </tr>\r\n"
			+ "                                                            </tbody>\r\n"
			+ "                                                        </table>\r\n"
			+ "                                                    </td>\r\n"
			+ "                                                </tr>\r\n"
			+ "                                            </tbody>\r\n"
			+ "                                        </table>\r\n"
			+ "                                    </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                            </tbody>\r\n"
			+ "                        </table>\r\n"
			+ "                    </td>\r\n"
			+ "                </tr>\r\n"
			+ "            </tbody>\r\n"
			+ "        </table>\r\n"
			+ "    </div>\r\n"
			+ "</body>\r\n"
			+ "<editor-card style=\"position:absolute;top:0px;left:0px;z-index:auto;display: block !important\">\r\n"
			+ "    <div dir=\"ltr\" style=\"all: initial;\">\r\n"
			+ "        <div style=\"color: initial; font: initial; font-feature-settings: initial; font-kerning: initial; font-optical-sizing: initial; font-synthesis: initial; font-variation-settings: initial; forced-color-adjust: initial; text-orientation: initial; text-rendering: initial; -webkit-font-smoothing: initial; -webkit-locale: initial; -webkit-text-orientation: initial; -webkit-writing-mode: initial; writing-mode: initial; zoom: initial; accent-color: initial; place-content: initial; place-items: initial; place-self: initial; alignment-baseline: initial; animation: initial; app-region: initial; appearance: initial; aspect-ratio: initial; backdrop-filter: initial; backface-visibility: initial; background: initial; background-blend-mode: initial; baseline-shift: initial; block-size: initial; border-block: initial; border: initial; border-radius: initial; border-collapse: initial; border-end-end-radius: initial; border-end-start-radius: initial; border-inline: initial; border-start-end-radius: initial; border-start-start-radius: initial; inset: initial; box-shadow: initial; box-sizing: initial; break-after: initial; break-before: initial; break-inside: initial; buffered-rendering: initial; caption-side: initial; caret-color: initial; clear: initial; clip: initial; clip-path: initial; clip-rule: initial; color-interpolation: initial; color-interpolation-filters: initial; color-rendering: initial; color-scheme: initial; columns: initial; column-fill: initial; gap: initial; column-rule: initial; column-span: initial; contain: initial; contain-intrinsic-block-size: initial; contain-intrinsic-size: initial; contain-intrinsic-inline-size: initial; content: initial; content-visibility: initial; counter-increment: initial; counter-reset: initial; counter-set: initial; cursor: initial; cx: initial; cy: initial; d: initial; display: initial; dominant-baseline: initial; empty-cells: initial; fill: initial; fill-opacity: initial; fill-rule: initial; filter: initial; flex: initial; flex-flow: initial; float: initial; flood-color: initial; flood-opacity: initial; grid: initial; grid-area: initial; height: initial; hyphens: initial; image-orientation: initial; image-rendering: initial; inline-size: initial; inset-block: initial; inset-inline: initial; isolation: initial; letter-spacing: initial; lighting-color: initial; line-break: initial; list-style: initial; margin-block: initial; margin: initial; margin-inline: initial; marker: initial; mask: initial; mask-type: initial; max-block-size: initial; max-height: initial; max-inline-size: initial; max-width: initial; min-block-size: initial; min-height: initial; min-inline-size: initial; min-width: initial; mix-blend-mode: initial; object-fit: initial; object-position: initial; offset: initial; opacity: initial; order: initial; origin-trial-test-property: initial; orphans: initial; outline: initial; outline-offset: initial; overflow-anchor: initial; overflow-clip-margin: initial; overflow-wrap: initial; overflow: initial; overscroll-behavior-block: initial; overscroll-behavior-inline: initial; overscroll-behavior: initial; padding-block: initial; padding: initial; padding-inline: initial; page: initial; page-orientation: initial; paint-order: initial; perspective: initial; perspective-origin: initial; pointer-events: initial; position: absolute; quotes: initial; r: initial; resize: initial; ruby-position: initial; rx: initial; ry: initial; scroll-behavior: initial; scroll-margin-block: initial; scroll-margin: initial; scroll-margin-inline: initial; scroll-padding-block: initial; scroll-padding: initial; scroll-padding-inline: initial; scroll-snap-align: initial; scroll-snap-stop: initial; scroll-snap-type: initial; scrollbar-gutter: initial; shape-image-threshold: initial; shape-margin: initial; shape-outside: initial; shape-rendering: initial; size: initial; speak: initial; stop-color: initial; stop-opacity: initial; stroke: initial; stroke-dasharray: initial; stroke-dashoffset: initial; stroke-linecap: initial; stroke-linejoin: initial; stroke-miterlimit: initial; stroke-opacity: initial; stroke-width: initial; tab-size: initial; table-layout: initial; text-align: initial; text-align-last: initial; text-anchor: initial; text-combine-upright: initial; text-decoration: initial; text-decoration-skip-ink: initial; text-indent: initial; text-overflow: initial; text-shadow: initial; text-size-adjust: initial; text-transform: initial; text-underline-offset: initial; text-underline-position: initial; touch-action: initial; transform: initial; transform-box: initial; transform-origin: initial; transform-style: initial; transition: initial; user-select: initial; vector-effect: initial; vertical-align: initial; visibility: initial; border-spacing: initial; -webkit-border-image: initial; -webkit-box-align: initial; -webkit-box-decoration-break: initial; -webkit-box-direction: initial; -webkit-box-flex: initial; -webkit-box-ordinal-group: initial; -webkit-box-orient: initial; -webkit-box-pack: initial; -webkit-box-reflect: initial; -webkit-highlight: initial; -webkit-hyphenate-character: initial; -webkit-line-break: initial; -webkit-line-clamp: initial; -webkit-mask-box-image: initial; -webkit-mask: initial; -webkit-mask-composite: initial; -webkit-perspective-origin-x: initial; -webkit-perspective-origin-y: initial; -webkit-print-color-adjust: initial; -webkit-rtl-ordering: initial; -webkit-ruby-position: initial; -webkit-tap-highlight-color: initial; -webkit-text-combine: initial; -webkit-text-decorations-in-effect: initial; -webkit-text-emphasis: initial; -webkit-text-emphasis-position: initial; -webkit-text-fill-color: initial; -webkit-text-security: initial; -webkit-text-stroke: initial; -webkit-transform-origin-x: initial; -webkit-transform-origin-y: initial; -webkit-transform-origin-z: initial; -webkit-user-drag: initial; -webkit-user-modify: initial; white-space: initial; widows: initial; width: initial; will-change: initial; word-break: initial; word-spacing: initial; x: initial; y: initial; z-index: 2147483647;\">\r\n"
			+ "            <link rel=\"stylesheet\" href=\"chrome-extension://hokifickgkhplphjiodbggjmoafhignh/fonts/fabric-icons.css\">\r\n"
			+ "            <div style=\"all: initial;\"></div>\r\n"
			+ "        </div>\r\n"
			+ "    </div>\r\n"
			+ "</editor-card>\r\n"
			+ "\r\n"
			+ "</html>";

}
